import { Dimensions, StyleSheet } from "react-native";

const { height: SCREEN_HEIGHT } = Dimensions.get("window");

export const styles = StyleSheet.create({
  fullContainer: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  headerBar: {
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitleGroup: {
    flex: 1,
  },
  aiTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#f5f3ff",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    alignSelf: "flex-start",
    marginBottom: 4,
    borderWidth: 1,
    borderColor: "#ddd6fe",
  },
  aiTagText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#7c3aed",
    textTransform: "uppercase",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0f172a",
  },
  closeBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  centerLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: "#64748b",
  },
  scrollBody: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
    gap: 16,
  },
  candidateScroll: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  candidateTab: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    alignItems: "center",
    minWidth: 110,
  },
  candidateTabActive: {
    backgroundColor: "#7c3aed",
    borderColor: "#7c3aed",
  },
  candidateTabRank: {
    fontSize: 12,
    fontWeight: "700",
    color: "#64748b",
  },
  candidateTabRankActive: {
    color: "#ffffff",
  },
  candidateTabScore: {
    fontSize: 16,
    fontWeight: "800",
    color: "#7c3aed",
    marginTop: 2,
  },
  candidateTabScoreActive: {
    color: "#ffffff",
  },
  heroCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  scoreBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#f0fdf4",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#86efac",
  },
  scoreBadgeText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#15803d",
  },
  conflictBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#fef2f2",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#fca5a5",
  },
  conflictBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#b91c1c",
  },
  heroTitle: {
    fontSize: 16.5,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 8,
  },
  summaryGrid: {
    flexDirection: "row",
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    padding: 12,
    justifyContent: "space-around",
    marginTop: 8,
  },
  summaryItem: {
    alignItems: "center",
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: "800",
    color: "#0f172a",
  },
  summaryLabel: {
    fontSize: 11,
    color: "#64748b",
    marginTop: 2,
  },
  sectionCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0f172a",
  },
  advantageItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 8,
  },
  advantageText: {
    flex: 1,
    fontSize: 13,
    color: "#166534",
    lineHeight: 18,
  },
  disadvantageItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 8,
  },
  disadvantageText: {
    flex: 1,
    fontSize: 13,
    color: "#991b1b",
    lineHeight: 18,
  },
  resourceRowCard: {
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  resourceTitle: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#1e293b",
  },
  resourceSub: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 3,
  },
  footerActionBar: {
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingHorizontal: 16,
    paddingTop: 12,
    flexDirection: "row",
    gap: 12,
  },
  applyBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#7c3aed",
    paddingVertical: 14,
    borderRadius: 12,
  },
  applyBtnText: {
    fontSize: 14.5,
    fontWeight: "700",
    color: "#ffffff",
  },
});
