import { StyleSheet } from "react-native";
import { Colors } from "../constants/colors";

export const styles = StyleSheet.create({
  fullContainer: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  headerBar: {
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitleGroup: {
    flex: 1,
    paddingRight: 10,
  },
  expBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#f0fdf4",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    alignSelf: "flex-start",
    marginBottom: 4,
    borderWidth: 1,
    borderColor: "#86efac",
  },
  expBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#15803d",
    textTransform: "uppercase",
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#0f172a",
  },
  closeBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  scrollBody: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
    gap: 16,
  },
  bannerCard: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  bannerTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: 4,
  },
  bannerSub: {
    fontSize: 12.5,
    color: "#64748b",
    lineHeight: 18,
  },
  dateBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  dateBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#475569",
  },
  // Tabs for Categories
  navTabsRow: {
    flexDirection: "row",
    gap: 8,
  },
  navTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  navTabActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  navTabText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#64748b",
  },
  navTabTextActive: {
    color: "#ffffff",
  },
  // Requirement Group
  reqGroupCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 12,
  },
  reqGroupHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  reqGroupTitleWrap: {
    flex: 1,
    paddingRight: 8,
  },
  reqGroupTitle: {
    fontSize: 14.5,
    fontWeight: "700",
    color: "#0f172a",
  },
  reqGroupSubtitle: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  countBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: "#cbd5e1",
  },
  countBadgeComplete: {
    backgroundColor: "#f0fdf4",
    borderColor: "#86efac",
  },
  countBadgeText: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#475569",
  },
  countBadgeTextComplete: {
    color: "#15803d",
  },
  // Resource Item Card
  resourceCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1.5,
    borderColor: "#e2e8f0",
    marginBottom: 8,
  },
  resourceCardSelected: {
    borderColor: Colors.primary,
    backgroundColor: "#f0fdf4",
  },
  resourceCardDisabled: {
    backgroundColor: "#f8fafc",
    borderColor: "#e2e8f0",
    opacity: 0.82,
  },
  resourceCardTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  checkboxWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  customCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#cbd5e1",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  customCheckboxChecked: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  customCheckboxDisabled: {
    backgroundColor: "#e2e8f0",
    borderColor: "#cbd5e1",
  },
  resourceMainInfo: {
    flex: 1,
  },
  resourceName: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#1e293b",
  },
  resourceCode: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  resourceMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
  metaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#f1f5f9",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  metaChipText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#475569",
  },
  // Status Reason Banner
  reasonBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
  },
  reasonBannerDisabled: {
    backgroundColor: "#fef2f2",
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  reasonBannerAvailable: {
    backgroundColor: "#f0fdf4",
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  reasonText: {
    flex: 1,
    fontSize: 11.5,
    fontWeight: "600",
    lineHeight: 16,
  },
  reasonTextDisabled: {
    color: "#b91c1c",
  },
  reasonTextAvailable: {
    color: "#15803d",
  },
  emptyListText: {
    fontSize: 13,
    color: "#94a3b8",
    textAlign: "center",
    paddingVertical: 12,
    fontStyle: "italic",
  },
  // Bottom Action Bar
  footerActionBar: {
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingHorizontal: 16,
    paddingTop: 12,
    flexDirection: "row",
    gap: 10,
  },
  aiBtn: {
    flex: 1.1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#7c3aed",
    paddingVertical: 13,
    borderRadius: 12,
  },
  aiBtnText: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#ffffff",
  },
  submitBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: Colors.primary,
    paddingVertical: 13,
    borderRadius: 12,
  },
  submitBtnDisabled: {
    backgroundColor: "#94a3b8",
  },
  submitBtnText: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#ffffff",
  },
  // Quantity-based Controls
  quantityCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
    borderColor: "#e2e8f0",
    gap: 12,
  },
  quantityCardCompleted: {
    borderColor: "#86efac",
    backgroundColor: "#ffffff",
  },
  quantityHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  quantityName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0f172a",
    lineHeight: 20,
  },
  quantityMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 4,
  },
  quantityCategoryText: {
    fontSize: 12,
    color: "#64748b",
  },
  quantityDot: {
    fontSize: 12,
    color: "#94a3b8",
  },
  quantityReqText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#475569",
  },
  quantityActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    backgroundColor: "#f8fafc",
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  stepperContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    overflow: "hidden",
  },
  stepperButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8fafc",
  },
  stepperButtonDisabled: {
    backgroundColor: "#f8fafc",
    opacity: 0.35,
  },
  stepperDisplay: {
    minWidth: 46,
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  stepperDisplayText: {
    fontSize: 14.5,
    fontWeight: "800",
    color: "#0f172a",
  },
  stepperDisplaySub: {
    fontSize: 11,
    fontWeight: "600",
    color: "#64748b",
    marginLeft: 2,
  },
  quickButtonsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 1,
  },
  quickSelectBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#cbd5e1",
  },
  quickSelectBtnActive: {
    backgroundColor: "#f0fdf4",
    borderColor: "#86efac",
  },
  quickSelectBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#475569",
  },
  quickSelectBtnTextActive: {
    color: "#15803d",
  },
  clearBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 8,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  clearBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748b",
  },
});
